server:
  port: 8081

#spring.output.ansi.enabled=ALWAYS

spring: 
    output.ansi.enabled: ALWAYS
    main:
        banner-mode: "CONSOLE"

#数据源配置
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

#开启包的自动扫描
entitymanager.packagesToScan: com.lrs.springboot.model
#Spring jpa data配置
spring.jpa:
  database: MYSQL
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

#Freemarker配置，参考配置：http://www.bysocket.com/p=1666/
spring.freemarker:
  template-loader-path: classpath:/web/
  cache: false
  charset: UTF-8
  check-template-location: true
  content-type: text/html
  expose-request-attributes: true
  expose-session-attributes: true
  request-context-attribute: request
  suffix: .ftl
  
 #Jackson配置
spring.jackson: 
  date-format: yyyy-MM-dd HH:mm:ss
  default-property-inclusion: non_null
  locale: zh_CN
  time-zone: GMT+8
  joda-date-time-format: yyyy-MM-dd HH:mm:ss

spring.redis:
 host: 127.0.0.1
 port: 6379
 ssl: false
 
#邮件配置
mail:
  host: 
  port: 25
  from:
  username:
  password:
  smtp: 
    protocol: 
    auth: true
    starttls-enable: true
    